# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2022-04-16 16:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('idempresa', models.IntegerField(help_text='Identificaci\xf3n de la Empresa', primary_key=True, serialize=False, verbose_name='Id Empresa')),
                ('emprfecha', models.DateTimeField(help_text='Fecha actualizada en la tabla Empresa', verbose_name='Fecha')),
                ('emprdesc', models.CharField(help_text='Descripci\xf3n de la Empresa', max_length=60, verbose_name='Descripcion')),
                ('empimage', models.CharField(help_text='Im\xe1gen que identifica la Empresa', max_length=60, verbose_name='Imagen')),
            ],
        ),
        migrations.CreateModel(
            name='Eqpconectados',
            fields=[
                ('equipo', models.CharField(help_text='Nombre del Equipo', max_length=60, verbose_name='Equipo')),
                ('direccionIpv4', models.CharField(help_text='Direcci\xf3n IPV4 4 octetos', max_length=60, primary_key=True, serialize=False, verbose_name='DireccionIpv4')),
                ('direccionIpv6', models.CharField(help_text='Direcci\xf3n IPV6 8 octetos', max_length=60, verbose_name='DireccionIpv6')),
                ('estado', models.IntegerField(help_text='El estado en <0> cuando el equipo no contesta y <1> si esta bien', verbose_name='Estado')),
                ('imagen', models.CharField(help_text='Im\xe1gen del equipo', max_length=100, verbose_name='Imagen')),
                ('imgEstado', models.CharField(help_text='Im\xe1gen que muestra el estado Ok o con problemas', max_length=100, verbose_name='Imagen de Estado')),
                ('descripcion', models.CharField(help_text='Descripci\xf3n breve del equipo ', max_length=100, verbose_name='Descripci\xf3n')),
                ('sensar', models.BooleanField(default=True, help_text='Est\xe1 en True para que se muestre por patalla', verbose_name='Sensar Equipo')),
                ('tipoEquipo', models.CharField(blank=True, choices=[('eqpse', 'Equipos Server'), ('eqpna', 'Equipos NAS'), ('eqpac', 'Equipos ACTIVOS'), ('eqpra', 'Equipos RADIOS')], default='-', help_text='Tipo de equipo a Sensar', max_length=6)),
            ],
            options={
                'ordering': ['equipo'],
            },
        ),
        migrations.CreateModel(
            name='Tablelog',
            fields=[
                ('idlog', models.IntegerField(primary_key=True, serialize=False)),
                ('equipo', models.CharField(max_length=60, verbose_name='Equipo')),
                ('direccionIpv6', models.CharField(max_length=60, verbose_name='Direccion IPv6')),
                ('fechaNove', models.DateTimeField(verbose_name='Fecha Novedad')),
                ('fechaRecup', models.DateTimeField(verbose_name='Fecha Recuperaci\xf3n')),
                ('evento', models.CharField(help_text='Evento', max_length=60, verbose_name='Evento ')),
                ('direccionIpv4', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gobequipos.Eqpconectados')),
            ],
            options={
                'ordering': ['fechaNove'],
            },
        ),
    ]
