# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2022-04-17 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gobequipos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablelog',
            name='idlog',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
