# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2022-04-18 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gobequipos', '0004_empresa_eqpconectados_tablelog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tablelog',
            options={'ordering': ['fechanove']},
        ),
        migrations.RenameField(
            model_name='eqpconectados',
            old_name='direccionIpv4',
            new_name='direccionipv4',
        ),
        migrations.RenameField(
            model_name='eqpconectados',
            old_name='direccionIpv6',
            new_name='direccionipv6',
        ),
        migrations.RenameField(
            model_name='eqpconectados',
            old_name='imgEstado',
            new_name='imgestado',
        ),
        migrations.RenameField(
            model_name='tablelog',
            old_name='direccionIpv4',
            new_name='direccionipv4',
        ),
        migrations.RenameField(
            model_name='tablelog',
            old_name='direccionIpv6',
            new_name='direccionipv6',
        ),
        migrations.RenameField(
            model_name='tablelog',
            old_name='fechaNove',
            new_name='fechanove',
        ),
        migrations.RenameField(
            model_name='tablelog',
            old_name='fechaRecup',
            new_name='fecharecup',
        ),
        migrations.AddField(
            model_name='eqpconectados',
            name='tipoequipo',
            field=models.CharField(default='-', help_text='Identificaci\xf3n interna del tipo ', max_length=10, verbose_name='Tipo Equipo'),
        ),
        migrations.AlterField(
            model_name='tablelog',
            name='idlog',
            field=models.IntegerField(help_text='Id registro en la tabla', primary_key=True, serialize=False, verbose_name='Id registro'),
        ),
    ]
