# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2022-04-18 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gobequipos', '0005_auto_20220418_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eqpconectados',
            name='tipoEquipo',
        ),
        migrations.AlterField(
            model_name='eqpconectados',
            name='imagen',
            field=models.CharField(blank=True, choices=[('EquipoActivoUp.gif', 'EQUIPO ACTIVO'), ('nasStorageUp.gif', 'EQUIPO NAS'), ('EquipoServer.gif', 'EQUIPO SERVER')], default='-', help_text='Imagen de Equipo', max_length=30),
        ),
        migrations.AlterField(
            model_name='eqpconectados',
            name='imgestado',
            field=models.CharField(blank=True, choices=[('EquipoActivoUp.gif', 'EQUIPO ACTIVO'), ('nasStorageUp.gif', 'EQUIPO NAS'), ('EquipoServer.gif', 'EQUIPO SERVER')], default='-', help_text='Imagen de Estado Equipo', max_length=30),
        ),
        migrations.AlterField(
            model_name='eqpconectados',
            name='tipoequipo',
            field=models.CharField(blank=True, choices=[('eqpse', 'Equipos Server'), ('eqpna', 'Equipos NAS'), ('eqpac', 'Equipos ACTIVOS'), ('eqpra', 'Equipos RADIOS')], default='-', help_text='Tipo de equipo a Sensar', max_length=6),
        ),
    ]
