# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2022-04-18 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gobequipos', '0011_auto_20220418_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eqpconectados',
            name='estado',
            field=models.IntegerField(default=1, help_text='El estado en <0> cuando el equipo no contesta y <1> si esta bien', verbose_name='Estado'),
        ),
    ]
