# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2022-04-18 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gobequipos', '0012_auto_20220418_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eqpconectados',
            name='imagen',
            field=models.CharField(help_text='Im\xe1gen del equipo', max_length=100, verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='eqpconectados',
            name='imgestado',
            field=models.CharField(help_text='Im\xe1gen que muestra el estado Ok o con problemas', max_length=100, verbose_name='Imagen de Estado'),
        ),
    ]
