# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2022-04-18 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gobequipos', '0013_auto_20220418_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eqpconectados',
            name='estado',
            field=models.IntegerField(blank=True, choices=[(1, 'Equipo Sensado OK'), (0, 'Equipos NAS')], default=1, help_text='Estado equipo Ok o NoOk'),
        ),
        migrations.AlterField(
            model_name='eqpconectados',
            name='imagen',
            field=models.CharField(blank=True, choices=[('EquipoActivoUp.gif', 'EQUIPO ACTIVO'), ('nasStorageUp.gif', 'EQUIPO NAS'), ('EquipoServer.gif', 'EQUIPO SERVER')], default='-', help_text='Imagen de Equipo', max_length=30),
        ),
        migrations.AlterField(
            model_name='eqpconectados',
            name='imgestado',
            field=models.CharField(blank=True, choices=[('EquipoActivoUp.gif', 'EQUIPO ACTIVO'), ('nasStorageUp.gif', 'EQUIPO NAS'), ('EquipoServer.gif', 'EQUIPO SERVER')], default='-', help_text='Imagen de Estado Equipo', max_length=30),
        ),
    ]
