# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2022-04-20 20:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gobequipos', '0015_auto_20220420_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablelog',
            name='direccionipv4',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gobequipos.Eqpconectados'),
        ),
    ]
