# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2022-04-21 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gobequipos', '0016_auto_20220420_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablelog',
            name='fechanove',
            field=models.DateTimeField(verbose_name='Fecha Novedad'),
        ),
        migrations.AlterField(
            model_name='tablelog',
            name='fecharecup',
            field=models.DateTimeField(verbose_name='Fecha Recuperaci\xf3n'),
        ),
    ]
